# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uic\mainform.ui'
#
# Created: Mon Jan 06 23:10:21 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(973, 497)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/new/icons/icons/app_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(1)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.mainLeftVLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.mainLeftVLayout.setSpacing(0)
        self.mainLeftVLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLeftVLayout.setObjectName("mainLeftVLayout")
        self.sourceBrowser = QtGui.QTreeWidget(self.layoutWidget)
        self.sourceBrowser.setMaximumSize(QtCore.QSize(16777215, 110))
        self.sourceBrowser.setAutoExpandDelay(-1)
        self.sourceBrowser.setAnimated(True)
        self.sourceBrowser.setHeaderHidden(False)
        self.sourceBrowser.setObjectName("sourceBrowser")
        item_0 = QtGui.QTreeWidgetItem(self.sourceBrowser)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/new/icons/icons/music-cd.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/new/icons/icons/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon2)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/new/icons/icons/playlist.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon3)
        item_0 = QtGui.QTreeWidgetItem(self.sourceBrowser)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/new/icons/icons/radio.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon4)
        self.mainLeftVLayout.addWidget(self.sourceBrowser)
        self.filterHLayout = QtGui.QHBoxLayout()
        self.filterHLayout.setSpacing(1)
        self.filterHLayout.setContentsMargins(3, 1, 1, 1)
        self.filterHLayout.setObjectName("filterHLayout")
        self.folderLbl = QtGui.QLabel(self.layoutWidget)
        self.folderLbl.setObjectName("folderLbl")
        self.filterHLayout.addWidget(self.folderLbl)
        self.folderCombo = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.folderCombo.sizePolicy().hasHeightForWidth())
        self.folderCombo.setSizePolicy(sizePolicy)
        self.folderCombo.setObjectName("folderCombo")
        self.filterHLayout.addWidget(self.folderCombo)
        self.libraryBtn = QtGui.QPushButton(self.layoutWidget)
        self.libraryBtn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/new/icons/icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.libraryBtn.setIcon(icon5)
        self.libraryBtn.setFlat(False)
        self.libraryBtn.setObjectName("libraryBtn")
        self.filterHLayout.addWidget(self.libraryBtn)
        self.mainLeftVLayout.addLayout(self.filterHLayout)
        self.sourceItemsBrowser = QtGui.QTreeView(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sourceItemsBrowser.sizePolicy().hasHeightForWidth())
        self.sourceItemsBrowser.setSizePolicy(sizePolicy)
        self.sourceItemsBrowser.setObjectName("sourceItemsBrowser")
        self.mainLeftVLayout.addWidget(self.sourceItemsBrowser)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.mainRightVLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.mainRightVLayout.setSpacing(1)
        self.mainRightVLayout.setContentsMargins(0, 0, 0, 0)
        self.mainRightVLayout.setObjectName("mainRightVLayout")
        self.playlist = QtGui.QTableWidget(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playlist.sizePolicy().hasHeightForWidth())
        self.playlist.setSizePolicy(sizePolicy)
        self.playlist.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.playlist.setTabKeyNavigation(False)
        self.playlist.setAlternatingRowColors(True)
        self.playlist.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.playlist.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.playlist.setGridStyle(QtCore.Qt.DotLine)
        self.playlist.setRowCount(10)
        self.playlist.setObjectName("playlist")
        self.playlist.setColumnCount(3)
        self.playlist.setRowCount(10)
        item = QtGui.QTableWidgetItem()
        self.playlist.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.playlist.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.playlist.setHorizontalHeaderItem(2, item)
        self.playlist.horizontalHeader().setDefaultSectionSize(200)
        self.playlist.verticalHeader().setVisible(True)
        self.playlist.verticalHeader().setDefaultSectionSize(19)
        self.mainRightVLayout.addWidget(self.playlist)
        self.controlsFrame = QtGui.QFrame(self.layoutWidget1)
        self.controlsFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.controlsFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.controlsFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.controlsFrame.setObjectName("controlsFrame")
        self.verticalLayout = QtGui.QVBoxLayout(self.controlsFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.controlsHLayout = QtGui.QHBoxLayout()
        self.controlsHLayout.setContentsMargins(9, 9, 9, 9)
        self.controlsHLayout.setObjectName("controlsHLayout")
        self.label = QtGui.QLabel(self.controlsFrame)
        self.label.setObjectName("label")
        self.controlsHLayout.addWidget(self.label)
        self.repeatBtn = QtGui.QPushButton(self.controlsFrame)
        self.repeatBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.repeatBtn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/new/icons/icons/media-repeat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.repeatBtn.setIcon(icon6)
        self.repeatBtn.setIconSize(QtCore.QSize(16, 16))
        self.repeatBtn.setFlat(True)
        self.repeatBtn.setObjectName("repeatBtn")
        self.controlsHLayout.addWidget(self.repeatBtn)
        spacerItem = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.controlsHLayout.addItem(spacerItem)
        self.previousBtn = QtGui.QPushButton(self.controlsFrame)
        self.previousBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.previousBtn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/new/icons/icons/media-previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previousBtn.setIcon(icon7)
        self.previousBtn.setIconSize(QtCore.QSize(24, 24))
        self.previousBtn.setFlat(False)
        self.previousBtn.setObjectName("previousBtn")
        self.controlsHLayout.addWidget(self.previousBtn)
        self.playPauseBtn = QtGui.QPushButton(self.controlsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playPauseBtn.sizePolicy().hasHeightForWidth())
        self.playPauseBtn.setSizePolicy(sizePolicy)
        self.playPauseBtn.setMinimumSize(QtCore.QSize(0, 0))
        self.playPauseBtn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/new/icons/icons/media-play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playPauseBtn.setIcon(icon8)
        self.playPauseBtn.setIconSize(QtCore.QSize(32, 32))
        self.playPauseBtn.setFlat(False)
        self.playPauseBtn.setObjectName("playPauseBtn")
        self.controlsHLayout.addWidget(self.playPauseBtn)
        self.stopBtn = QtGui.QPushButton(self.controlsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopBtn.sizePolicy().hasHeightForWidth())
        self.stopBtn.setSizePolicy(sizePolicy)
        self.stopBtn.setMinimumSize(QtCore.QSize(0, 0))
        self.stopBtn.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/new/icons/icons/media-stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopBtn.setIcon(icon9)
        self.stopBtn.setIconSize(QtCore.QSize(32, 32))
        self.stopBtn.setFlat(False)
        self.stopBtn.setObjectName("stopBtn")
        self.controlsHLayout.addWidget(self.stopBtn)
        self.nextBtn = QtGui.QPushButton(self.controlsFrame)
        self.nextBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.nextBtn.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/new/icons/icons/media-next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextBtn.setIcon(icon10)
        self.nextBtn.setIconSize(QtCore.QSize(24, 24))
        self.nextBtn.setFlat(False)
        self.nextBtn.setObjectName("nextBtn")
        self.controlsHLayout.addWidget(self.nextBtn)
        spacerItem1 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.controlsHLayout.addItem(spacerItem1)
        self.shuffleBtn = QtGui.QPushButton(self.controlsFrame)
        self.shuffleBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.shuffleBtn.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/new/icons/icons/media-shuffle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shuffleBtn.setIcon(icon11)
        self.shuffleBtn.setIconSize(QtCore.QSize(16, 16))
        self.shuffleBtn.setFlat(True)
        self.shuffleBtn.setObjectName("shuffleBtn")
        self.controlsHLayout.addWidget(self.shuffleBtn)
        spacerItem2 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.controlsHLayout.addItem(spacerItem2)
        self.horizontalSlider = QtGui.QSlider(self.controlsFrame)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setInvertedControls(False)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.controlsHLayout.addWidget(self.horizontalSlider)
        self.horizontalSlider_2 = QtGui.QSlider(self.controlsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_2.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_2.setSizePolicy(sizePolicy)
        self.horizontalSlider_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.controlsHLayout.addWidget(self.horizontalSlider_2)
        self.verticalLayout.addLayout(self.controlsHLayout)
        self.mainRightVLayout.addWidget(self.controlsFrame)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 973, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuPlayback = QtGui.QMenu(self.menubar)
        self.menuPlayback.setObjectName("menuPlayback")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPlayback.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Woofer", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceBrowser.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Playback source", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceBrowser.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "ID", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.sourceBrowser.isSortingEnabled()
        self.sourceBrowser.setSortingEnabled(False)
        self.sourceBrowser.topLevelItem(0).setText(0, QtGui.QApplication.translate("MainWindow", "Music", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceBrowser.topLevelItem(0).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Folders", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceBrowser.topLevelItem(0).child(0).setText(1, QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceBrowser.topLevelItem(0).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Playlists", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceBrowser.topLevelItem(0).child(1).setText(1, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceBrowser.topLevelItem(1).setText(0, QtGui.QApplication.translate("MainWindow", "Radios", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceBrowser.topLevelItem(1).setText(1, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceBrowser.setSortingEnabled(__sortingEnabled)
        self.folderLbl.setText(QtGui.QApplication.translate("MainWindow", "Folder:", None, QtGui.QApplication.UnicodeUTF8))
        self.playlist.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.playlist.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Favorite", None, QtGui.QApplication.UnicodeUTF8))
        self.playlist.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Duration", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "Media", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPlayback.setTitle(QtGui.QApplication.translate("MainWindow", "Playback", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
